# Generated by Django 5.2.6 on 2025-09-26 21:45

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='file_data',
            field=models.FileField(blank=True, null=True, upload_to=files.models.upload_path),
        ),
    ]
