# Generated by Django 5.2.6 on 2025-09-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_fileitem_file_data'),
        ('files', '0002_create_default_folders'),
    ]

    operations = [
    ]
